dependencies:
- name: bdd-gh-1587775390
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1587775390
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-import-1587777775
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1587775390
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbrp-import-1587777775
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1587774311
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
